export const SERVER_PORT = 'PORT';
export const JWT_SECRET =
  'xn5rXERz8N6QDFf-36mvNupIzfKEWSZjBczLlsss7Xh-5woHz5jMdoNDyMdhaZ8N-fBbU7QGzhyFwHiCZ4lKuSsPRt0WhLA8vGnen8FbS67s0tW3dU8f8jCE4IjMs8YyIxJWcc22Aty_Gq0acMAQKW3RoChJn89EJBebjpg8slk';

export const TYPEORM_CONFIG = 'database.config';
/**
export const DATABASE_HOST = 'DATABASE_HOST';
export const DATABASE_PORT = 'DATABASE_PORT';
export const DATABASE_USERNAME = 'DATABASE_USERNAME';
export const DATABASE_PASSWORD = 'DATABASE_PASSWORD';
export const DATABASE_NAME = 'DATABASE_NAME';
 */

export const DEFAULT_USER_EMAIL = 'DEFAULT_USER_EMAIL';
export const DETAULT_USER_PASSWORD = 'DETAULT_USER_PASSWORD';
